### ISSUE TITLE
429 Error Attribute Error

### ISSUE THREAD

**Issue by BenA-SA** [rocketreach/rocketreach_python#5]
Hi, 

Not sure if anyone is monitoring or maintaining this, but if so, there's a bug here.

I'm getting an error when I try and lookup a person - it looks like I'm getting a 429, which then gives an error.

AttributeError: 'NoneType' object has no attribute 'group'

From line 95 in _execute_lookup in person_gateway.py

m = re.search(r'Expected available in (\d+) second', result.message).group(1)

**Comment by bristobal** [comment]
could you resolve it? I'm having the same issue...

**Comment by BenA-SA** [comment]
No, I spoke to one of their developers who said this package is no longer maintained, so I switched to using their main API using requests instead

**Comment by punihaole** [comment]
This package wont support bulk lookups, but if that's not something you require you can continue using it. We have a fix for this bug.

https://github.com/rocketreach/rocketreach_python/pull/6

**Comment by punihaole** [comment]
Please try version 2.1.7 (just released) https://pypi.org/project/rocketreach/2.1.7/

**Comment by punihaole** [comment]
Closing this issue since it was solved in 2.1.7
